esphome:
  name: mechanische-ventilatie
  friendly_name: mechanische_ventilatie
  libraries:
    - SPI
    - Ticker

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

external_components:
  - source:
      type: git
      url: https://github.com/CrazyChaos/esphome_ct
      ref: main
#    refresh: 3600s # only set this briefly otherwise it just refreshes daily, see https://esphome.io/components/external_components#external-components-refresh for setting refresh too low

# Enable logging
logger:
  level: DEBUG # Change this to VERBOSE to find out the ID of your remote.

fan:
  - platform: "cc1101"
    speed_count: 3
    name: "Mechanical Fan"
    data_pin: D1
    map_off_to_zero: True
    id: mech_fan

button:
  - platform: template
    name: "Send join command"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->send_other_command(0);
  - platform: template
    name: "Run Timer for 10 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->send_other_command(1);
  - platform: template
    name: "Run Timer for 20 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->send_other_command(2);
  - platform: template
    name: "Run Timer for 30 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->send_other_command(3);
  - platform: template
    name: "Set speed low"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->set_fan_speed(1);
  - platform: template
    name: "Set speed medium"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->set_fan_speed(2);
  - platform: template
    name: "Set speed high"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(id(mech_fan)))->set_fan_speed(3);
